import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import CreatePost from './create-post';
import CreatePartner from './create-partner';
import hotelImg from "../img/Hotel1.png";
import partnerImg from "../img/partner.png";
import { useState } from 'react';


export default function Home() {
  const [openHotel, setOpenHotel] = useState(false)
  const [openPartner, setOpenPartner] = useState(false);
  
  const handleBookHotel = () => {
    setOpenHotel(true)
  }
  const handleBookPartner = () => {
    setOpenPartner(true);
  };
  const handleClose = () => {
    setOpenHotel(false);
  };
  const handleClosePartner = () => {
    setOpenPartner(false);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container pt-10">
        <div className="p-10 main-bg">
          <div className="flex  justify-between items-center h-[60vh]">
            <div className="w-full">
              <div className="flex flex-col justify-between md:flex-row">
                <div className="w-[60%]">
                  <h3 className="text-4xl md:text-5xl">
                    Click to create Post based on <br />
                    <span className="font-bold">Category</span>
                  </h3>
                </div>

                <div className="md:w-[30%]">
                  <div className="p-4 space-y-4 bg-white rounded-xl">
                    <button onClick={handleBookHotel}>
                      <div className="px-4 pt-2 bg-[#DFE8FF] rounded-2xl">
                        <div className="flex items-center justify-between text-left">
                          <div className="w-[40%]">
                            <Image src={hotelImg} alt=""/>
                          </div>
                          <div className="w-[60%]">
                            <p className="text-xl font-semibold">
                              Already Booked
                            </p>
                            <p className="text-sm">
                              My hotel is booked just looking for partner
                            </p>
                          </div>
                        </div>
                      </div>
                    </button>
                    <button className="w-full" onClick={handleBookPartner}>
                      <div className="px-4 pt-2 bg-[#FFD6D6] rounded-2xl w-full">
                        <div className="flex items-center justify-between text-left">
                          <div className="w-[50%]">
                            <p className="text-xl font-semibold">
                              Finding partner
                            </p>
                            <p className="text-sm">
                              I’m looking for travel partner
                            </p>
                          </div>

                          <div className="w-[30%]">
                            <Image src={partnerImg} alt=""/>
                          </div>
                        </div>
                      </div>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <CreatePost openModal={openHotel} closeModal={handleClose} />
        <CreatePartner openPartnerModal={openPartner} closePartnerModal={handleClosePartner} />
      </main>
    </div>
  );
}
